package VO;
// Generated 28 ene. 2020 12:02:16 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Articulo generated by hbm2java
 */
public class Articulo  implements java.io.Serializable {


     private int artiId;
     private String artiNombre;
     private int artiValorunitario;
     private int artiExistencia;
     private Date artiFechacambio;
     private String artiResgistradopor;

    public Articulo() {
    }

    public Articulo(String artiNombre, int artiValorunitario, int artiExistencia) {
        this.artiNombre = artiNombre;
        this.artiValorunitario = artiValorunitario;
        this.artiExistencia = artiExistencia;
    }

    public Articulo(int artiId, String artiNombre, int artiValorunitario, int artiExistencia, Date artiFechacambio, String artiResgistradopor) {
        this.artiId = artiId;
        this.artiNombre = artiNombre;
        this.artiValorunitario = artiValorunitario;
        this.artiExistencia = artiExistencia;
        this.artiFechacambio = artiFechacambio;
        this.artiResgistradopor = artiResgistradopor;
    }
    
    
	
  
    
   
    public int getArtiId() {
        return this.artiId;
    }
    
    public void setArtiId(int artiId) {
        this.artiId = artiId;
    }
    public String getArtiNombre() {
        return this.artiNombre;
    }
    
    public void setArtiNombre(String artiNombre) {
        this.artiNombre = artiNombre;
    }
    public int getArtiValorunitario() {
        return this.artiValorunitario;
    }
    
    public void setArtiValorunitario(int artiValorunitario) {
        this.artiValorunitario = artiValorunitario;
    }
    public int getArtiExistencia() {
        return this.artiExistencia;
    }
    
    public void setArtiExistencia(int artiExistencia) {
        this.artiExistencia = artiExistencia;
    }
    public Date getArtiFechacambio() {
        return this.artiFechacambio;
    }
    
    public void setArtiFechacambio(Date artiFechacambio) {
        this.artiFechacambio = artiFechacambio;
    }
    public String getArtiResgistradopor() {
        return this.artiResgistradopor;
    }
    
    public void setArtiResgistradopor(String artiResgistradopor) {
        this.artiResgistradopor = artiResgistradopor;
    }
   




}


