package VO;
// Generated 28 ene. 2020 12:02:16 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int clieId;
     private String clieDocumento;
     private String clieNombre;
     private String clieApellido;
     private String clieDireccion;
     private String clieTelefono;
     private String clieEmail;
     private Date clieFechacambio;
     private String clieRegistradopor;

    public Cliente() {
    }

    public Cliente(String clieDocumento, String clieNombre, String clieApellido, String clieDireccion, String clieTelefono, String clieEmail) {
        this.clieDocumento = clieDocumento;
        this.clieNombre = clieNombre;
        this.clieApellido = clieApellido;
        this.clieDireccion = clieDireccion;
        this.clieTelefono = clieTelefono;
        this.clieEmail = clieEmail;
    }

    public Cliente(int clieId, String clieDocumento, String clieNombre, String clieApellido, String clieDireccion, String clieTelefono, String clieEmail, Date clieFechacambio, String clieRegistradopor) {
        this.clieId = clieId;
        this.clieDocumento = clieDocumento;
        this.clieNombre = clieNombre;
        this.clieApellido = clieApellido;
        this.clieDireccion = clieDireccion;
        this.clieTelefono = clieTelefono;
        this.clieEmail = clieEmail;
        this.clieFechacambio = clieFechacambio;
        this.clieRegistradopor = clieRegistradopor;
    }

	
  
   
    public int getClieId() {
        return this.clieId;
    }
    
    public void setClieId(int clieId) {
        this.clieId = clieId;
    }
    public String getClieDocumento() {
        return this.clieDocumento;
    }
    
    public void setClieDocumento(String clieDocumento) {
        this.clieDocumento = clieDocumento;
    }
    public String getClieNombre() {
        return this.clieNombre;
    }
    
    public void setClieNombre(String clieNombre) {
        this.clieNombre = clieNombre;
    }
    public String getClieApellido() {
        return this.clieApellido;
    }
    
    public void setClieApellido(String clieApellido) {
        this.clieApellido = clieApellido;
    }
    public String getClieDireccion() {
        return this.clieDireccion;
    }
    
    public void setClieDireccion(String clieDireccion) {
        this.clieDireccion = clieDireccion;
    }
    public String getClieTelefono() {
        return this.clieTelefono;
    }
    
    public void setClieTelefono(String clieTelefono) {
        this.clieTelefono = clieTelefono;
    }
    public String getClieEmail() {
        return this.clieEmail;
    }
    
    public void setClieEmail(String clieEmail) {
        this.clieEmail = clieEmail;
    }
    public Date getClieFechacambio() {
        return this.clieFechacambio;
    }
    
    public void setClieFechacambio(Date clieFechacambio) {
        this.clieFechacambio = clieFechacambio;
    }
    public String getClieRegistradopor() {
        return this.clieRegistradopor;
    }
    
    public void setClieRegistradopor(String clieRegistradopor) {
        this.clieRegistradopor = clieRegistradopor;
    }

    @Override
    public String toString() {
        return "Cliente{" + "clieId=" + clieId + ", clieDocumento=" + clieDocumento + ", clieNombre=" + clieNombre + ", clieApellido=" + clieApellido + ", clieDireccion=" + clieDireccion + ", clieTelefono=" + clieTelefono + ", clieEmail=" + clieEmail + '}';
    }
  




}


