package VO;
// Generated 28 ene. 2020 12:02:16 by Hibernate Tools 4.3.1



import java.util.Date;

/**
 * Detallefactura generated by hbm2java
 */
public class DetalleFactura  implements java.io.Serializable {


     private int defaId;
     private Articulo articulo;
     private FacturaCliente facturacliente;
     private int defaCantidad;
     private int defaValorunitario;
     private Date defaFechacambio;
     private String defaRegistardopor;
     private int artiId;
    public DetalleFactura() {
    }

    public DetalleFactura(Articulo articulo, FacturaCliente facturacliente, int defaCantidad) {
        this.articulo = articulo;
        this.facturacliente = facturacliente;
        this.defaCantidad = defaCantidad;
        this.defaValorunitario=articulo.getArtiValorunitario();
    }

    public DetalleFactura(int defaId, int artiId, int defaCantidad, int defaValorunitario, Date defaFechacambio, String defaRegistardopor) {
        this.defaId = defaId;
        this.artiId = artiId;
        this.defaCantidad = defaCantidad;
        this.defaValorunitario = defaValorunitario;
        this.defaFechacambio = defaFechacambio;
        this.defaRegistardopor = defaRegistardopor;
    }

   

    
   
   
    public int getDefaId() {
        return this.defaId;
    }
    
    public void setDefaId(int defaId) {
        this.defaId = defaId;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public FacturaCliente getFacturacliente() {
        return this.facturacliente;
    }
    
    public void setFacturacliente(FacturaCliente facturacliente) {
        this.facturacliente = facturacliente;
    }
    public int getDefaCantidad() {
        return this.defaCantidad;
    }
    
    public void setDefaCantidad(int defaCantidad) {
        this.defaCantidad = defaCantidad;
    }
    public int getDefaValorunitario() {
        return this.defaValorunitario;
    }
    
    public void setDefaValorunitario(int defaValorunitario) {
        this.defaValorunitario = defaValorunitario;
    }
    public Date getDefaFechacambio() {
        return this.defaFechacambio;
    }
    
    public void setDefaFechacambio(Date defaFechacambio) {
        this.defaFechacambio = defaFechacambio;
    }
    public String getDefaRegistardopor() {
        return this.defaRegistardopor;
    }
    
    public void setDefaRegistardopor(String defaRegistardopor) {
        this.defaRegistardopor = defaRegistardopor;
    }

    public int getArtiId() {
        return artiId;
    }

    public void setArtiId(int artiId) {
        this.artiId = artiId;
    }

    @Override
    public String toString() {
        return "Detallefactura{" + "defaId=" + defaId + ", articulo=" + articulo +  ", defaCantidad=" + defaCantidad + ", defaValorunitario=" + defaValorunitario + ", defaFechacambio=" + defaFechacambio + ", defaRegistardopor=" + defaRegistardopor + '}';
    }




}


