package VO;
// Generated 28 ene. 2020 12:02:16 by Hibernate Tools 4.3.1


import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Facturacliente generated by hbm2java
 */
public class FacturaCliente  implements java.io.Serializable {


     private int faclId;
     private int clieId;
     private Cliente cliente;
     private int faclTotal;
     private Date faclFecha;
     private Date faclFechacambio;
     private String faclRegistradopor;
     private ArrayList<DetalleFactura> detallefacturas;

    public FacturaCliente() {
    }

    public FacturaCliente(Cliente cliente) {
        this.cliente = cliente;
        this.faclTotal=0;
        this.detallefacturas=new ArrayList();
        this.faclFecha=  new Date();
        this.faclFechacambio=new Date();
    }
  private String fecha(){
      SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
          String fechaComoCadena = sdf.format(this.faclFecha);
            return fechaComoCadena;
  }

    public int getClieId() {
        return clieId;
    }

    public void setClieId(int clieId) {
        this.clieId = clieId;
    }
    
     
    public FacturaCliente(int faclId, int cliente, int faclTotal, Date faclFecha, Date faclFechacambio, String faclRegistradopor) {
        this.faclId = faclId;
        this.clieId= cliente;
        this.faclTotal = faclTotal;
        this.faclFecha = faclFecha;
        this.faclFechacambio = faclFechacambio;
        this.faclRegistradopor = faclRegistradopor;
    }

	
    
   
    public int getFaclId() {
        return this.faclId;
    }
    
    public void setFaclId(int faclId) {
        this.faclId = faclId;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    
    public int getFaclTotal() {
        return this.faclTotal;
    }
    
    public void setFaclTotal(int faclTotal) {
        this.faclTotal = faclTotal;
    }
    public Date getFaclFecha() {
        return this.faclFecha;
    }
    
    public void setFaclFecha(Date faclFecha) {
        this.faclFecha = faclFecha;
    }
    public Date getFaclFechacambio() {
        return this.faclFechacambio;
    }
    
    public void setFaclFechacambio(Date faclFechacambio) {
        this.faclFechacambio = faclFechacambio;
    }
    public String getFaclRegistradopor() {
        return this.faclRegistradopor;
    }
    
    public void setFaclRegistradopor(String faclRegistradopor) {
        this.faclRegistradopor = faclRegistradopor;
    }
    public List<DetalleFactura> getDetallefacturas() {
        return this.detallefacturas;
    }
    
    public void setDetallefacturas(ArrayList<DetalleFactura> detallefacturas) {
        this.detallefacturas = detallefacturas;
    }

    
    public void AgregarArticulo(int cant,Articulo articulo){
        this.detallefacturas.add(new DetalleFactura(articulo, this,cant));
        this.faclTotal=this.faclTotal+(cant*articulo.getArtiValorunitario());
    }
    
    public DetalleFactura eliminarArticulo(int index){
        DetalleFactura detalle=this.detallefacturas.remove(index);
        this.faclTotal=this.faclTotal-(detalle.getDefaCantidad()*detalle.getArticulo().getArtiValorunitario());
        return detalle;
    }

    @Override
    public String toString() {
        return "Facturacliente{" + "faclId=" + faclId + ", cliente=" + cliente + ", faclTotal=" + faclTotal + ", faclFecha=" + faclFecha + ", faclFechacambio=" + faclFechacambio + ", faclRegistradopor=" + faclRegistradopor + '}';
    }

    
    
    



}


